"use client";

import { useEffect, useState } from "react";
type User = { id: string; email: string; full_name: string; role: string; is_active: boolean; created_at: string };
export default function AdminUsersPage() {
  const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/admin/users"); const body = await response.json(); if (!response.ok) throw new Error(body.error); setUsers(body.users); }
  useEffect(() => { load().catch((reason: Error) => setError(reason.message)); }, []);
  async function toggle(user: User) { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: user.id, is_active: !user.is_active }) }); if (!response.ok) setError((await response.json()).error); else load(); }
  return <div><p className="text-sm font-semibold uppercase tracking-widest text-muted">Management</p><h1 className="mt-2 font-core text-3xl font-semibold">Users</h1>{error && <p className="mt-6 rounded-soft bg-[#ffe9e9] px-4 py-3 text-sm text-[#a51d2d]">{error}</p>}<section className="mt-8 overflow-hidden rounded-card bg-white shadow-card"><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-line/50 bg-canvas text-xs uppercase tracking-widest text-muted"><tr><th className="px-5 py-4">Email</th><th className="px-5 py-4">Name</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Created</th><th className="px-5 py-4 text-right">Status</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-b border-line/30 last:border-0"><td className="px-5 py-4 font-semibold">{user.email}</td><td className="px-5 py-4 text-muted">{user.full_name || "-"}</td><td className="px-5 py-4 capitalize text-muted">{user.role}</td><td className="px-5 py-4 text-muted">{new Date(user.created_at).toLocaleDateString()}</td><td className="px-5 py-4 text-right"><button onClick={() => toggle(user)} className={`rounded-pill px-3 py-1 text-xs font-semibold ${user.is_active ? "bg-[#e7f7ec] text-[#176b35]" : "bg-[#ffe9e9] text-[#a51d2d]"}`}>{user.is_active ? "Active" : "Disabled"}</button></td></tr>)}</tbody></table></div>{!users.length && !error && <p className="p-8 text-center text-sm text-muted">No users found.</p>}</section></div>;
}
