"use client";

import { useEffect, useState } from "react";

type Dashboard = { counts: { products: number; users: number; orders: number; pending: number; completed: number }; recentOrders: { id: string; status: string; total: number; created_at: string }[] };

export default function AdminDashboardPage() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/admin/dashboard").then(async (response) => { if (!response.ok) throw new Error((await response.json()).error); return response.json(); }).then(setDashboard).catch((reason: Error) => setError(reason.message)); }, []);
  const cards = dashboard ? [{ label: "Products", value: dashboard.counts.products }, { label: "Users", value: dashboard.counts.users }, { label: "Orders", value: dashboard.counts.orders }, { label: "Pending orders", value: dashboard.counts.pending }, { label: "Delivered orders", value: dashboard.counts.completed }] : [];
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-muted">Overview</p><h1 className="mt-2 font-core text-3xl font-semibold">Dashboard</h1></div><span className="rounded-pill bg-white px-4 py-2 text-sm font-semibold text-muted">Live database metrics</span></div>{error && <p className="mt-6 rounded-soft bg-[#ffe9e9] px-4 py-3 text-sm text-[#a51d2d]">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map((card) => <div key={card.label} className="rounded-card bg-white p-5 shadow-card"><p className="text-sm text-muted">{card.label}</p><p className="mt-3 font-core text-3xl font-semibold">{card.value}</p></div>)}{!dashboard && !error && <p className="text-sm text-muted">Loading dashboard...</p>}</div><section className="mt-8 rounded-card bg-white p-6 shadow-card"><div className="flex items-center justify-between"><h2 className="font-core text-xl font-semibold">Recent orders</h2><span className="text-sm text-muted">Last 5</span></div><div className="mt-5 overflow-x-auto">{dashboard?.recentOrders.length ? <table className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-line/50 text-xs uppercase tracking-widest text-muted"><tr><th className="pb-3">Order</th><th className="pb-3">Date</th><th className="pb-3">Status</th><th className="pb-3 text-right">Total</th></tr></thead><tbody>{dashboard.recentOrders.map((order) => <tr key={order.id} className="border-b border-line/30 last:border-0"><td className="py-4 font-semibold">{order.id.slice(0, 8)}</td><td className="py-4 text-muted">{new Date(order.created_at).toLocaleDateString()}</td><td className="py-4 capitalize text-muted">{order.status}</td><td className="py-4 text-right font-semibold">${Number(order.total).toFixed(2)}</td></tr>)}</tbody></table> : <p className="py-8 text-sm text-muted">No orders yet.</p>}</div></section></div>;
}
